name: roflit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  # roflit_s3: ^0.0.1
  roflit_s3:
    path: ../roflit_s3

  # aws_signature_v4: ^0.5.1
  http: ^1.2.2
  file_picker: ^8.0.6
  # chopper: ^7.1.1
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  uuid: ^4.4.0
  # riverpod & hooks
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.4
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  #
  easy_debounce: ^2.0.3
  dio: ^5.4.1
  json_annotation: ^4.8.1
  easy_localization: ^3.0.4
  go_router: ^13.2.0
  permission_handler: ^11.3.0
  # window_manager: ^0.3.8
  desktop_window: ^0.4.1
  file_selector: ^1.0.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.3.1
  # drift
  drift: ^2.20.3
  sqlite3_flutter_libs: ^0.5.24
  sqlite3: ^2.4.6
  path: ^1.9.0
  path_provider: ^2.1.4
  #
  xml2json: ^6.2.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # riverpod
  custom_lint: ^0.6.2
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  #  drift
  drift_dev: ^2.20.3
  drift_db_viewer: ^2.1.0
  flutter_gen_runner: ^5.4.0 # //$ GOOD

flutter:
  uses-material-design: true

  assets:
    # - assets/app/images/
    - assets/translations/
    - assets/icons/

  # fonts:
  #   - family: Ubuntu-Regular
  #     fonts:
  #       - asset: assets/app/fonts/text/Ubuntu-Regular.ttf
  #         weight: 400
  #   - family: Ubuntu-Bold
  #     fonts:
  #       - asset: assets/app/fonts/text/Ubuntu-Bold.ttf
  #         weight: 700
  #   - family: icons
  #     fonts:
  #       - asset: assets/app/fonts/icons/icons.ttf

flutter_gen:
  output: lib/generated
  line_length: 120
  integrations:
    flutter_svg: true

    # git:
    #   url: https://github.com/KubrickRubrik/roflit_s3.git
    #   ref: master
