name: roflit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  aws_signature_v4: ^0.2.1
  chopper: ^7.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  easy_debounce: ^2.0.3
  dio: ^5.4.1
  json_annotation: ^4.8.1
  path: ^1.9.0
  easy_localization: ^3.0.4
  path_provider: ^2.1.2
  go_router: ^13.2.0
  permission_handler: ^11.3.0
  flutter_riverpod: ^2.4.10
  # window_manager: ^0.3.8
  desktop_window: ^0.4.0
  file_selector: ^1.0.3
  file_picker: ^6.1.1
  # flutter_dropzone: ^3.0.7
  # flutter_dropzone_platform_interface: ^2.0.6

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  chopper_generator: ^7.1.1
  custom_lint: ^0.6.2
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  assets:
  # - assets/app/images/
  - assets/translations/

  # fonts:
  #   - family: Ubuntu-Regular
  #     fonts:
  #       - asset: assets/app/fonts/text/Ubuntu-Regular.ttf
  #         weight: 400
  #   - family: Ubuntu-Bold
  #     fonts:
  #       - asset: assets/app/fonts/text/Ubuntu-Bold.ttf
  #         weight: 700
  #   - family: icons
  #     fonts:
  #       - asset: assets/app/fonts/icons/icons.ttf

flutter_gen:
  output: lib/generated
  line_length: 120

